ENSEMBLE_LLM_MODEL=qwen3-4b-instruct-2507-ud-q4_k_xl
ENSEMBLE_HOST_MODEL_DIR=./models
ENSEMBLE_MODEL_PATH=/models/qwen3-4b-instruct-2507-ud-q4_k_xl.gguf
ENSEMBLE_MODEL_ALIAS=qwen3-4b-instruct-2507-ud-q4_k_xl
ENSEMBLE_N_CTX=32768
ENSEMBLE_N_THREADS=6
ENSEMBLE_SERVER_PORT=8888
